name       : gradience
version    : 0.3.1
release    : 1
source     :
    - https://github.com/GradienceTeam/Gradience/archive/refs/tags/0.3.1.tar.gz : f0cea2c68165732ac2a5ca0f6266c497b774b6e9b20a78a8e4c2e4bf7fc024b4
license    : GPL-3.0-or-later
homepage   : https://gradienceteam.github.io/
component  : desktop
summary    : Change the look of Adwaita, with ease
description: |
    Gradience is a tool for customizing Libadwaita applications and the adw-gtk3 theme
builddeps  :
    - pkgconfig(blueprint-compiler)
    - pkgconfig(gtk4)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(pygobject-3.0)
    - desktop-file-utils
    - python-lxml
rundeps    :
    - libadwaita
    - libportal
    - material-color-utilities-python
    - python-anyascii
    - python-cssutils
    - python-jinja
    - python-svglib
    - python-yapsy
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
