name       : gradience
version    : 0.3.2
release    : 2
source     :
    - https://github.com/GradienceTeam/Gradience/archive/refs/tags/0.3.2.tar.gz : 98c05473ca6e71230dc64ffa862299558188625a9ffcb0c2349686ebc83e813b
license    : GPL-3.0-or-later
homepage   : https://gradienceteam.github.io/
component  : desktop
summary    : Change the look of Adwaita, with ease
description: |
    Gradience is a tool for customizing Libadwaita applications and the adw-gtk3 theme
builddeps  :
    - pkgconfig(blueprint-compiler)
    - pkgconfig(gtk4)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(pygobject-3.0)
    - desktop-file-utils
    - python-lxml
rundeps    :
    - libadwaita
    - libportal
    - material-color-utilities-python
    - python-anyascii
    - python-jinja
    - python-svglib
    - python-yapsy
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
